# device settings
[devices]
    [devices.h1]
        name = "h1"
        ip = "10.0.0.1"
        cmd = ["sysctl -w net.ipv4.tcp_congestion_control=cubic"]
    [devices.h2]
        name = "h2"
        ip = "10.0.0.2"
        cmd = ["sysctl -w net.ipv4.tcp_congestion_control=cubic"]

# switch settings
[switches]
    [switches.s1]
        name = "s1"
    [switches.s2]
        name = "s2"

# link settings
[links]
pairs = [
    ["h1", "s1"],
    ["s1", "s2"],
    ["s2", "h2"]
]

# root commands for configuring network
[root]
cmd = [
    "sudo tc qdisc replace dev s1-eth2 root handle 10: tbf rate 100mbit burst 50000 limit 150000",
    "sudo tc qdisc add dev s1-eth2 parent 10: handle 20: netem loss 0.01% delay 30ms 7ms distribution normal",
    "sudo tc qdisc replace dev s1-eth1 root handle 10: tbf rate 100mbit burst 50000 limit 150000",
    "sudo tc qdisc add dev s1-eth1 parent 10: handle 20: netem loss 0.01% delay 30ms 7ms distribution normal",
    "sudo tc qdisc replace dev s2-eth2 root handle 10: tbf rate 50mbit burst 25000 limit 75000",
    "sudo tc qdisc add dev s2-eth2 parent 10: handle 15: red limit 60Mbit avpkt 1000 probability 0.1 bandwidth 100Mbit",
    "sudo tc qdisc replace dev s2-eth1 root handle 10: tbf rate 50mbit burst 25000 limit 75000",

]
